# Generated by Django 3.2.13 on 2022-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('home_team', models.CharField(max_length=250)),
                ('home_goals', models.CharField(max_length=3)),
                ('away_goals', models.CharField(max_length=3)),
                ('away_team', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
